using UnityEngine;

[RequireComponent(typeof(Rigidbody))]
[RequireComponent(typeof(Collider))]
public class BalaTorretaLogica : MonoBehaviour
{
    public int daÃ±o = 10;
    private bool impacto;

    void Start()
    {
        Destroy(gameObject, 8f);
    }

    void OnCollisionEnter(Collision collision)
    {
        if (impacto) return;

        // ðŸ”¥ BUSCAR PlayerSalud EN EL PADRE
        PlayerSalud salud = collision.collider.GetComponentInParent<PlayerSalud>();

        if (salud != null)
        {
            salud.RecibirDaÃ±o(daÃ±o);
            Debug.Log("BALA TORRETA â†’ VIDA REDUCIDA");

            impacto = true;
            Destroy(gameObject);
            return;
        }

        // Destruir si choca con cualquier cosa que no sea la torreta
        if (!collision.gameObject.CompareTag("Torreta"))
        {
            impacto = true;
            Destroy(gameObject);
        }
    }
}
